# Generated by Django 6.0.2 on 2026-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_email_listing_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='email',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='phone',
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
