# Generated by Django 6.0.2 on 2026-03-27 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='engine_power',
            field=models.PositiveIntegerField(blank=True, help_text='Ot kuchi', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='fuel_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='l/100km', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='max_speed',
            field=models.PositiveIntegerField(blank=True, help_text='Km/soat', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='seats',
            field=models.PositiveSmallIntegerField(blank=True, help_text="O'rindiqlar soni", null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('pickup', 'Pickup Truck'), ('van', 'Van'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
