# Generated by Django 6.0.2 on 2026-03-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_engine_power_listing_fuel_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='engine_power',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='fuel_consumption',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='max_speed',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='seats',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
